### ISSUE TITLE
New pulleys touch each other

### ISSUE THREAD

**Issue by qgeissmann** [PolygonalTree/ethoscope_hardware#7]
The new design (#4) of the double-o-ring pulleys is great, but because servos are not homogeneously laid-out, some pulley touch neighbouring ones.

A simple solution, at this stage, is to unscrew/re-screw servos to allow around 3mm of gap.

@pepelisu It would be nice to reprint a module at some point soon though.

**Comment by qgeissmann** [comment]
A simple solution is to space servos a bit more. This can be achieved by 3d printing the base with hole templates.

**Comment by pepelisu** [comment]
ready to print
