### ISSUE TITLE
Arena targets cannot be seen at night

### ISSUE THREAD

**Issue by qgeissmann** [PolygonalTree/ethoscope_hardware#9]
New startegies for targets:
- they should be cut in vinyl  (4mm diam.)
- the arena should have a\* _square_\* indentation to stick them
- a hole below the taget should be made to be able to see the targets at all time (the hole/box should be larget than the target , so we have contrast).

**Comment by pepelisu** [comment]
new base printing...now the box is a square of 4mm by 4mm lets see if that is enough for the light or we need a bigger hole/box

**Comment by qgeissmann** [comment]
I am pretty confident you need a slightly larger "light" box. otherwise, the circle will appear merged to the arena -> little contrast.

**Comment by ggilestro** [comment]
If IR light is reflected from above, the easiest solution may be to buy
some safety reflective sticker like these ones (
http://www.amazon.co.uk/Scotchlite-Reflective-Stickers-Rectangles-reflects/dp/B00TFP8KPS/ref=sr_1_cc_3?s=aps&ie=UTF8&qid=1442406461&sr=1-3-catcorr&keywords=safety+reflective+stickers
) and place a circle of it on the target. A way for doing this could be:
- [x] print a square indentation on the arena
- [ ] cut a square of safety reflective material of about the the same size
  and place it in the indentation
- [ ]  print a square frame with an internal circular hole and place it
  above

I've ordered some to test right now.

## 

Giorgio F. Gilestro
http://gilest.ro

**Comment by qgeissmann** [comment]
This is not super convincing, but the solution with **large** hollow boxes under the targets seems to work:

![dark_targets](https://cloud.githubusercontent.com/assets/1399684/9997595/f204ea98-6084-11e5-983a-2e0e9e16b84c.png)

You may need to change contrast to see the targets...

This will be improved by
1. printing vinyl target stickers that are round (so we don't have the shadow of the paper)
2. More homogeneous and vertical light diffusion (see #8).
